import type { ReactNode } from 'react';
import {
  Calendar,
  Stethoscope,
  ShieldCheck,
  Activity,
  HeartPulse,
  AlertTriangle,
  ShieldAlert,
  Grid3X3,
  Target,
  TrendingUp,
  Pill,
  Flame,
  Baby,
  Wind,
  Droplets,
  Thermometer,
  Heart,
  Gauge,
  FlaskConical,
  AlertCircle,
  BookOpen,
} from 'lucide-react';
import type { HospitalWardId } from '../types/wards';

export interface ToolItem {
  id: string;
  title: string;
  shortTitle: string;
  subtitle: string;
  badge: string;
  ward: HospitalWardId;
  keywords: string[];
  icon: ReactNode;
}

export const TOOLS: ToolItem[] = [
  // ==========================================
  // INTERNAL MEDICINE (7)
  // ==========================================
  {
    id: 'ckd_crcl',
    title: 'CKD-EPI 2021 eGFR & CrCl',
    shortTitle: 'CKD-EPI / CrCl',
    subtitle: 'Race-free chronic kidney disease staging & Cockcroft-Gault renal dosing clearance',
    badge: 'KDIGO 2024',
    ward: 'internal_medicine',
    keywords: ['egfr', 'ckd', 'creatinine', 'crcl', 'cockcroft', 'kidney', 'gfr', 'renal', 'dosing', 'ibw'],
    icon: <Activity className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'afib_anticoag',
    title: 'CHA₂DS₂-VASc & HAS-BLED Suite',
    shortTitle: 'CHA₂DS₂-VASc',
    subtitle: 'Atrial fibrillation annual ischemic stroke risk & bleeding safety for DOAC selection',
    badge: 'AHA/ACC 2024',
    ward: 'internal_medicine',
    keywords: ['afib', 'atrial fibrillation', 'chads', 'cha2ds2', 'hasbled', 'anticoagulation', 'doac', 'apixaban', 'warfarin', 'stroke'],
    icon: <HeartPulse className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'wells_vte',
    title: 'Wells PE & DVT / PERC Rule',
    shortTitle: 'Wells PE / DVT',
    subtitle: 'Pulmonary embolism & deep vein thrombosis pretest probability with D-dimer / CTPA pathways',
    badge: 'CHEST / ESC',
    ward: 'internal_medicine',
    keywords: ['wells', 'pe', 'dvt', 'perc', 'pulmonary embolism', 'thrombosis', 'd-dimer', 'ctpa', 'vte', 'clot'],
    icon: <ShieldAlert className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />,
  },
  {
    id: 'curb65',
    title: 'CURB-65 Pneumonia Severity',
    shortTitle: 'CURB-65',
    subtitle: 'Community-acquired pneumonia 30-day mortality risk & outpatient vs inpatient/ICU triage',
    badge: 'ATS / IDSA',
    ward: 'internal_medicine',
    keywords: ['curb', 'curb65', 'pneumonia', 'cap', 'mortality', 'bun', 'confusion', 'icu', 'inpatient'],
    icon: <AlertCircle className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'psi_port',
    title: 'PSI / PORT Pneumonia Severity',
    shortTitle: 'PSI / PORT',
    subtitle: 'Fine et al. 20-variable prognostic risk index & ATS/IDSA disposition criteria',
    badge: 'Fine / NEJM',
    ward: 'internal_medicine',
    keywords: ['psi', 'port', 'pneumonia', 'fine', 'cap', 'mortality', 'inpatient', 'icu', 'pleural effusion'],
    icon: <Activity className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />,
  },
  {
    id: 'liver_meld_child',
    title: 'MELD-Na 2016 & Child-Pugh',
    shortTitle: 'MELD-Na / Child',
    subtitle: 'End-stage cirrhosis 90-day waitlist mortality & Child-Turcotte-Pugh surgical risk class',
    badge: 'UNOS / AASLD',
    ward: 'internal_medicine',
    keywords: ['meld', 'meld-na', 'child', 'child-pugh', 'cirrhosis', 'liver', 'hepatology', 'ascites', 'encephalopathy', 'inr', 'bilirubin'],
    icon: <Target className="w-5 h-5 text-orange-600 dark:text-orange-400" />,
  },
  {
    id: 'electrolytes',
    title: 'Electrolytes & Acid-Base Suite',
    shortTitle: 'Electrolytes / AG',
    subtitle: 'Katz/Hillier corrected sodium in hyperglycemia, serum osmolality gap & corrected anion gap',
    badge: 'Internal Med',
    ward: 'internal_medicine',
    keywords: ['sodium', 'hyperglycemia', 'osmolality', 'osmolar gap', 'anion gap', 'delta', 'dka', 'acidosis', 'acid-base'],
    icon: <FlaskConical className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },

  // ==========================================
  // GENERAL SURGERY & TRAUMA (7)
  // ==========================================
  {
    id: 'parkland_burn',
    title: 'Parkland Burn & Rule of Nines',
    shortTitle: 'Parkland Burn',
    subtitle: 'Adult & pediatric TBSA% calculator, 8h/16h Lactated Ringer’s rates & urine output goals',
    badge: 'ABA Consensus',
    ward: 'surgery',
    keywords: ['burn', 'parkland', 'tbsa', 'fluid resuscitation', 'rule of nines', 'trauma', 'lactated ringers', 'baxter', 'pediatric burn'],
    icon: <Flame className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'appendicitis',
    title: 'Alvarado & AIR Appendicitis Scores',
    shortTitle: 'Alvarado / AIR',
    subtitle: 'Right lower quadrant pain diagnostic checklist, imaging thresholds & appendectomy criteria',
    badge: 'WSES Jerusalem',
    ward: 'surgery',
    keywords: ['alvarado', 'air', 'appendicitis', 'rlq', 'mantrels', 'rebound', 'leukocytosis', 'laparoscopy'],
    icon: <Activity className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'rcri_cardiac',
    title: 'Revised Cardiac Risk Index (RCRI)',
    shortTitle: 'RCRI Cardiac',
    subtitle: 'Lee index for preoperative noncardiac surgical clearance & 30-day MACE prediction',
    badge: 'ACC / AHA',
    ward: 'surgery',
    keywords: ['rcri', 'lee', 'cardiac risk', 'preop', 'clearance', 'mace', 'myocardial infarction', 'surgery'],
    icon: <Heart className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'goldman_nsqip',
    title: 'Goldman & ACS NSQIP Surgical Risk',
    shortTitle: 'Goldman / NSQIP',
    subtitle: 'Original multifactorial cardiac index & universal 30-day morbidity/mortality prediction',
    badge: 'ACS NSQIP',
    ward: 'surgery',
    keywords: ['goldman', 'nsqip', 'surgical risk', 'cardiac risk', 'asa', 'morbidity', 'preoperative', 'mortality', 'ssi'],
    icon: <HeartPulse className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'caprini_vte',
    title: 'Caprini Surgical VTE Score',
    shortTitle: 'Caprini VTE',
    subtitle: 'Postoperative thromboembolism risk stratification, mechanical IPC & LMWH chemoprophylaxis',
    badge: 'CHEST 2012',
    ward: 'surgery',
    keywords: ['caprini', 'vte', 'dvt', 'prophylaxis', 'lmwh', 'enoxaparin', 'ipc', 'surgical risk'],
    icon: <ShieldCheck className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />,
  },
  {
    id: 'surgical_apgar',
    title: 'Surgical Apgar Score (SAS)',
    shortTitle: 'Surgical Apgar',
    subtitle: 'Intraoperative lowest MAP, lowest HR, and EBL predicting major 30-day complications',
    badge: 'Gawande / JACS',
    ward: 'surgery',
    keywords: ['surgical apgar', 'sas', 'gawande', 'ebl', 'map', 'blood loss', 'pacu', 'complications'],
    icon: <Gauge className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },
  {
    id: 'pancreatitis',
    title: 'Glasgow-Imrie Pancreatitis Criteria',
    shortTitle: 'Glasgow Pancreas',
    subtitle: 'PANCREAS mnemonic assessing acute pancreatitis severity & organ failure within 48 hours',
    badge: 'BSG Standard',
    ward: 'surgery',
    keywords: ['glasgow', 'imrie', 'pancreatitis', 'pancreas', 'amylase', 'lipase', 'acute abdomen'],
    icon: <AlertCircle className="w-5 h-5 text-yellow-600 dark:text-yellow-400" />,
  },

  // ==========================================
  // PEDIATRICS & RESUSCITATION (7)
  // ==========================================
  {
    id: 'pediatric_gcs',
    title: 'Pediatric Glasgow Coma Scale (PGCS)',
    shortTitle: 'Pediatric GCS',
    subtitle: 'Infant (<2y) and child neurological assessment with trauma airway intubation rules',
    badge: 'PALS / AAP',
    ward: 'pediatrics',
    keywords: ['pediatric gcs', 'pgcs', 'coma', 'glasgow', 'pediatric brain injury', 'tbi', 'neurology', 'pecarn'],
    icon: <Baby className="w-5 h-5 text-sky-600 dark:text-sky-400" />,
  },
  {
    id: 'holliday_segar',
    title: 'Holliday-Segar Fluids & Deficit',
    shortTitle: 'Holliday-Segar',
    subtitle: '100/50/20 daily & 4/2/1 hourly maintenance rates + % dehydration deficit replacement',
    badge: 'AAP Guideline',
    ward: 'pediatrics',
    keywords: ['holliday', 'segar', 'pediatric fluids', 'maintenance', 'dehydration', 'deficit', 'isotonic', 'iv fluids'],
    icon: <Droplets className="w-5 h-5 text-blue-500 dark:text-blue-400" />,
  },
  {
    id: 'pediatric_airway',
    title: 'Pediatric Airway & Resuscitation',
    shortTitle: 'Peds Airway / ETT',
    subtitle: 'Khine cuffed/uncuffed ETT size & depth, PALS defibrillation energy, cardiac arrest epinephrine',
    badge: 'PALS 2020',
    ward: 'pediatrics',
    keywords: ['ett', 'endotracheal', 'khine', 'cuffed', 'defibrillation', 'pals', 'airway', 'resuscitation', 'laryngoscope'],
    icon: <Wind className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'pediatric_bp_vitals',
    title: 'Pediatric Blood Pressure & Vitals',
    shortTitle: 'Peds BP & Vitals',
    subtitle: 'AAP 2017 age/sex/height blood pressure percentiles, HTN staging & normal vitals',
    badge: 'AAP 2017',
    ward: 'pediatrics',
    keywords: ['pediatric blood pressure', 'bp percentiles', 'hypertension', 'vitals', 'aap', 'pals', 'hypotension', 'heart rate'],
    icon: <Heart className="w-5 h-5 text-rose-500 dark:text-rose-400" />,
  },
  {
    id: 'pediatric_dosing',
    title: 'Pediatric Weight-Based Drug Dosing',
    shortTitle: 'Weight Dosing',
    subtitle: 'Acetaminophen, Ibuprofen, high-dose Amoxicillin, Epinephrine 1:1,000 & D10W bolus (mg & mL)',
    badge: 'AAP Consensus',
    ward: 'pediatrics',
    keywords: ['pediatric dosing', 'tylenol', 'paracetamol', 'ibuprofen', 'motrin', 'amoxicillin', 'epinephrine', 'd10w', 'liquid volume'],
    icon: <Pill className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />,
  },
  {
    id: 'mcisaac_strep',
    title: 'Centor / McIsaac Strep Pharyngitis',
    shortTitle: 'Centor / McIsaac',
    subtitle: 'Modified Centor score for Group A Streptococcus probability, RADT testing & antibiotic triage',
    badge: 'IDSA / AAP',
    ward: 'pediatrics',
    keywords: ['centor', 'mcisaac', 'strep', 'pharyngitis', 'sore throat', 'group a strep', 'radt', 'tonsillitis'],
    icon: <Thermometer className="w-5 h-5 text-rose-500 dark:text-rose-400" />,
  },
  {
    id: 'pram_asthma',
    title: 'Pediatric Asthma Severity (PRAM)',
    shortTitle: 'PRAM Asthma',
    subtitle: 'Validated 12-point clinical score for acute pediatric asthma exacerbations & bronchodilator triage',
    badge: 'CTS Standard',
    ward: 'pediatrics',
    keywords: ['pram', 'asthma', 'pediatric asthma', 'wheezing', 'retractions', 'albuterol', 'salbutamol', 'steroids', 'respiratory'],
    icon: <Activity className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },

  // ==========================================
  // OBSTETRICS & GYNECOLOGY (11)
  // ==========================================
  {
    id: 'dating',
    title: 'ACOG 700 Pregnancy Dating',
    shortTitle: 'ACOG Dating',
    subtitle: 'LMP vs Ultrasound dating reconciliation per ACOG Committee Opinion 700',
    badge: 'ACOG CO 700',
    ward: 'obgyn',
    keywords: ['dating', 'edd', 'ga', 'gestational age', 'crl', 'lmp', 'ultrasound', 'due date', 'trimester'],
    icon: <Calendar className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'bishop',
    title: 'Bishop Score & Cervical Ripening',
    shortTitle: 'Bishop Score',
    subtitle: 'Assessment of cervical readiness for induction of labor with simplified scoring',
    badge: 'ACOG Practice',
    ward: 'obgyn',
    keywords: ['bishop', 'cervix', 'induction', 'ripening', 'effacement', 'dilation', 'station', 'misoprostol', 'foley'],
    icon: <Stethoscope className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },
  {
    id: 'vbac',
    title: 'VBAC Success Predictor',
    shortTitle: 'VBAC Grobman',
    subtitle: 'Grobman race-neutral MFMU model predicting trial of labor success after cesarean',
    badge: 'MFMU Consensus',
    ward: 'obgyn',
    keywords: ['vbac', 'tolac', 'cesarean', 'grobman', 'uterine rupture', 'vaginal birth'],
    icon: <ShieldCheck className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />,
  },
  {
    id: 'fetal_growth',
    title: 'Hadlock 4-Parameter EFW & Fluid',
    shortTitle: 'Hadlock EFW',
    subtitle: 'Estimated fetal weight from BPD/HC/AC/FL and amniotic fluid assessment (AFI/SDP)',
    badge: 'SMFM Guidelines',
    ward: 'obgyn',
    keywords: ['efw', 'hadlock', 'ultrasound', 'fetal weight', 'bpd', 'hc', 'ac', 'fl', 'afi', 'sdp', 'oligohydramnios', 'polyhydramnios'],
    icon: <Activity className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />,
  },
  {
    id: 'apgar',
    title: 'Apgar Score Calculator',
    shortTitle: 'Apgar Score',
    subtitle: 'Newborn physiological status at 1, 5, and 10 minutes with resuscitation guidance',
    badge: 'AAP / NRP',
    ward: 'obgyn',
    keywords: ['apgar', 'neonatal', 'newborn', 'resuscitation', 'nrp', 'appearance', 'pulse', 'grimace', 'activity', 'respiration'],
    icon: <HeartPulse className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'preeclampsia',
    title: 'Preeclampsia with Severe Features',
    shortTitle: 'Preeclampsia',
    subtitle: 'ACOG Practice Bulletin 222 diagnostic criteria and hypertensive emergency protocols',
    badge: 'ACOG PB 222',
    ward: 'obgyn',
    keywords: ['preeclampsia', 'hypertension', 'blood pressure', 'severe features', 'labetalol', 'hydralazine', 'nifedipine', 'proteinuria', 'platelets', 'creatinine', 'headache', 'delivery timing'],
    icon: <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'hemorrhage',
    title: 'CMQCC Obstetric Hemorrhage & QBL',
    shortTitle: 'Postpartum QBL',
    subtitle: 'Quantified blood loss calculator, stage-based hemorrhage protocols and MTP activation',
    badge: 'CMQCC 2022',
    ward: 'obgyn',
    keywords: ['hemorrhage', 'pph', 'qbl', 'blood loss', 'uterotonic', 'oxytocin', 'methergine', 'hemabate', 'misoprostol', 'txa', 'mtp', 'transfusion'],
    icon: <ShieldAlert className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'popq',
    title: 'POP-Q Staging System',
    shortTitle: 'POP-Q Staging',
    subtitle: 'Pelvic Organ Prolapse Quantification 9-point grid and Baden-Walker conversion',
    badge: 'ICS / IUGA',
    ward: 'obgyn',
    keywords: ['popq', 'prolapse', 'pelvic organ', 'cystocele', 'rectocele', 'apical', 'baden-walker', 'gh', 'pb', 'tvl', 'stage'],
    icon: <Grid3X3 className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'ovarian',
    title: 'Ovarian Mass RMI Calculator',
    shortTitle: 'Ovarian RMI',
    subtitle: 'Risk of Malignancy Index (RMI I) combining ultrasound score, menopausal status, and CA-125',
    badge: 'RCOG Green-top',
    ward: 'obgyn',
    keywords: ['rmi', 'ovarian mass', 'adnexal', 'ca125', 'malignancy', 'ultrasound', 'menopause', 'gynecologic oncology'],
    icon: <Target className="w-5 h-5 text-fuchsia-600 dark:text-fuchsia-400" />,
  },
  {
    id: 'hcg',
    title: 'Serum hCG Kinetics in PUL',
    shortTitle: 'hCG Kinetics',
    subtitle: 'Expected 48-hour rise/fall thresholds and ectopic pregnancy risk stratification',
    badge: 'ACOG PB 193',
    ward: 'obgyn',
    keywords: ['hcg', 'kinetics', 'doubling time', 'ectopic', 'pul', 'pregnancy of unknown location', 'methotrexate', 'discriminatory zone'],
    icon: <TrendingUp className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'dosing',
    title: 'Ward Dosing: Iron Deficit & Rhogam',
    shortTitle: 'Iron / Rhogam',
    subtitle: 'Ganzoni formula for IV iron replacement and Kleihauer-Betke calculation for anti-D immune globulin',
    badge: 'ACOG PB 181',
    ward: 'obgyn',
    keywords: ['ganzoni', 'iron deficit', 'anemia', 'ferric derisomaltose', 'rhogam', 'anti-d', 'kleihauer-betke', 'fmh', 'fetomaternal hemorrhage'],
    icon: <Pill className="w-5 h-5 text-violet-600 dark:text-violet-400" />,
  },

  // ==========================================
  // EXPANDED WARD SUITES
  // ==========================================
  // Internal Medicine Expanded
  {
    id: 'cardiology_suite',
    title: 'Cardiology & ACS Risk Suite',
    shortTitle: 'Cardio & ACS',
    subtitle: 'TIMI UA/NSTEMI, HEART Score, Killip classification & QTc rate correction',
    badge: 'ACC / AHA / ESC',
    ward: 'internal_medicine',
    keywords: ['timi', 'heart', 'killip', 'qtc', 'bazett', 'fridericia', 'cardiology', 'acs', 'nstemi', 'chest pain', 'troponin', 'angina', 'mace', 'grace', 'nyha', 'ascvd'],
    icon: <HeartPulse className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'critical_care_suite',
    title: 'Critical Care & Pulmonology Suite',
    shortTitle: 'Critical Care / Pulm',
    subtitle: 'SOFA, qSOFA, Light’s criteria, Berlin ARDS staging & A-a oxygen gradient',
    badge: 'Sepsis-3 / ATS',
    ward: 'internal_medicine',
    keywords: ['sofa', 'qsofa', 'sepsis', 'lights', 'pleural effusion', 'exudate', 'transudate', 'ards', 'berlin', 'p/f ratio', 'aa gradient', 'alveolar gas', 'hypoxemia', 'icu'],
    icon: <Wind className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />,
  },
  {
    id: 'renal_fluids_suite',
    title: 'Nephrology, Acid-Base & Fluids Suite',
    shortTitle: 'Renal & Acid-Base',
    subtitle: 'FENa, FEUrea, Winter’s formula compensation, Free water deficit & Corrected calcium',
    badge: 'KDIGO / Acid-Base',
    ward: 'internal_medicine',
    keywords: ['fena', 'feurea', 'prerenal', 'atn', 'winters', 'metabolic acidosis', 'paco2', 'free water deficit', 'hypernatremia', 'sodium correction', 'corrected calcium', 'hypoalbuminemia'],
    icon: <FlaskConical className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'neuro_systemic_suite',
    title: 'Neurology & Systemic Medicine Suite',
    shortTitle: 'Neuro & Systemic',
    subtitle: 'ABCD² TIA stroke risk, SIRS, Dengue warning signs, Mentzer Index & Absolute Neutrophil Count',
    badge: 'AHA/ASA / WHO',
    ward: 'internal_medicine',
    keywords: ['abcd2', 'tia', 'stroke risk', 'sirs', 'dengue', 'warning signs', 'mentzer', 'thalassemia', 'anc', 'neutrophil', 'neutropenia', 'hematology', 'nihss', 'gcs'],
    icon: <Activity className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },

  // Surgery Expanded
  {
    id: 'trauma_acute_suite',
    title: 'Trauma & Acute Resuscitation Suite',
    shortTitle: 'Trauma & Resusc',
    subtitle: 'Revised Trauma Score (RTS), ABC Score for MTP, Shock Index & Modified Baux Burn Score',
    badge: 'ATLS / ACS-COT',
    ward: 'surgery',
    keywords: ['rts', 'revised trauma', 'abc score', 'mtp', 'massive transfusion', 'shock index', 'msi', 'baux', 'modified baux', 'burn mortality', 'trauma center', 'hemorrhage', 'fast exam'],
    icon: <Flame className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'surgical_preop_suite',
    title: 'Preoperative & Nursing Risk Suite',
    shortTitle: 'Pre-Op & Nursing',
    subtitle: 'ASA physical status, Mallampati, STOP-BANG OSA, Ankle-Brachial Index & Braden scale',
    badge: 'ASA / AHA / Braden',
    ward: 'surgery',
    keywords: ['asa', 'mallampati', 'stop-bang', 'osa', 'sleep apnea', 'abi', 'ankle brachial', 'pad', 'braden', 'pressure ulcer', '4-2-1 fluids', 'maintenance fluids', 'preoperative'],
    icon: <ShieldCheck className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },

  // Pediatrics Expanded
  {
    id: 'neonatology_nicu_suite',
    title: 'Neonatology & NICU Suite',
    shortTitle: 'Neonatology / NICU',
    subtitle: 'New Ballard score, Silverman-Andersen respiratory distress, Corrected age & Mid-parental height',
    badge: 'AAP / NICU',
    ward: 'pediatrics',
    keywords: ['ballard', 'new ballard', 'gestational age', 'preterm', 'silverman', 'silverman-andersen', 'respiratory distress', 'corrected age', 'prematurity', 'mid-parental height', 'tanner target', 'nicu'],
    icon: <Baby className="w-5 h-5 text-sky-600 dark:text-sky-400" />,
  },
  {
    id: 'peds_emergency_suite',
    title: 'Pediatric Emergency & Infectious Suite',
    shortTitle: 'Peds Emergency',
    subtitle: 'Westley croup score, PECARN pediatric head injury rules & Kawasaki disease diagnostic evaluation',
    badge: 'PECARN / AHA',
    ward: 'pediatrics',
    keywords: ['croup', 'westley', 'stridor', 'epinephrine', 'dexamethasone', 'pecarn', 'head injury', 'citbi', 'tbi', 'ct head', 'kawasaki', 'strawberry tongue', 'coronary aneurysm', 'ivig'],
    icon: <ShieldAlert className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },

  // OB/GYN Expanded
  {
    id: 'antenatal_fetal_suite',
    title: 'Antenatal & Fetal Surveillance Suite',
    shortTitle: 'Antenatal & Fetal',
    subtitle: 'McDonald fundal height discrepancy, Manning Biophysical Profile (BPP) & Carpenter-Coustan GDM OGTT',
    badge: 'ACOG / Manning',
    ward: 'obgyn',
    keywords: ['fundal height', 'mcdonald', 'iugr', 'macrosomia', 'bpp', 'biophysical profile', 'nst', 'fetal breathing', 'gdm', 'ogtt', 'carpenter-coustan', 'gestational diabetes', 'glucose tolerance'],
    icon: <Heart className="w-5 h-5 text-pink-600 dark:text-pink-400" />,
  },
  {
    id: 'high_risk_maternal_suite',
    title: 'High-Risk Obstetrics & Labor Suite',
    shortTitle: 'High-Risk & Labor',
    subtitle: 'HELLP syndrome (Mississippi class), NICHD 3-tier FHR category & HELPERR shoulder dystocia protocol',
    badge: 'ACOG / NICHD',
    ward: 'obgyn',
    keywords: ['hellp', 'mississippi class', 'thrombocytopenia', 'ldh', 'ast', 'fhr', 'nichd', 'category i', 'category ii', 'category iii', 'decelerations', 'variability', 'helperr', 'shoulder dystocia', 'mcroberts', 'rubin'],
    icon: <ShieldAlert className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'gyn_endocrine_suite',
    title: 'Gynecologic Endocrinology Suite',
    shortTitle: 'Gyn Endocrinology',
    subtitle: 'Rotterdam PCOS diagnostic criteria & Modified Ferriman-Gallwey hirsutism scoring',
    badge: 'Rotterdam / ESHRE',
    ward: 'obgyn',
    keywords: ['pcos', 'rotterdam', 'polycystic ovary', 'hyperandrogenism', 'anovulation', 'ferriman-gallwey', 'hirsutism', 'testosterone', 'gyn oncology', 'endocrine'],
    icon: <Pill className="w-5 h-5 text-pink-600 dark:text-pink-400" />,
  },

  // ==========================================
  // CLINICAL WIKI MASTER SUITES & TOOLS
  // ==========================================
  // Internal Medicine Wiki Tools
  {
    id: 'medicine_wiki_suite',
    title: 'Medicine Clinical Wiki Master Suite',
    shortTitle: 'Medicine Wiki',
    subtitle: 'ASCVD 10-year risk, GRACE ACS, Geneva PE, SAAG ascites, Maddrey mDF, 4Ts HIT & Burch-Wartofsky',
    badge: 'ACC / ESC / AASLD',
    ward: 'internal_medicine',
    keywords: ['ascvd', 'grace', 'geneva', 'saag', 'maddrey', '4ts', 'hit', 'burch-wartofsky', 'thyroid storm', 'friedewald', 'ldl', 'kdigo', 'aki', 'gbs', 'glasgow-blatchford', 'apache ii', 'gold copd'],
    icon: <HeartPulse className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'ascvd_risk',
    title: 'ASCVD 10-Year Risk Estimator',
    shortTitle: 'ASCVD Risk',
    subtitle: 'ACC/AHA 2018 Pooled Cohort Equations predicting 10-year atherosclerotic cardiovascular event risk',
    badge: 'AHA / ACC 2018',
    ward: 'internal_medicine',
    keywords: ['ascvd', 'pooled cohort', 'cardiovascular risk', 'statin', 'cholesterol', 'framingham', 'prevention', 'coronary'],
    icon: <HeartPulse className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'grace_score',
    title: 'GRACE ACS Mortality Score',
    shortTitle: 'GRACE Score',
    subtitle: 'In-hospital & 6-month mortality risk stratification and angiography timing in acute coronary syndromes',
    badge: 'ESC ACS 2023',
    ward: 'internal_medicine',
    keywords: ['grace', 'acs', 'nstemi', 'stemi', 'mortality', 'killip', 'coronary angiography', 'troponin', 'cardiac arrest'],
    icon: <Activity className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'geneva_pe',
    title: 'Revised Geneva PE Pretest Score',
    shortTitle: 'Geneva PE',
    subtitle: 'Alternative to Wells for pulmonary embolism pretest probability and D-dimer vs CTPA triage',
    badge: 'ESC / ERS',
    ward: 'internal_medicine',
    keywords: ['geneva', 'pe', 'pulmonary embolism', 'dvt', 'vte', 'ctpa', 'd-dimer', 'hemoptysis', 'tachycardia'],
    icon: <Wind className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />,
  },
  {
    id: 'saag_ascites',
    title: 'SAAG Ascites Gradient & Portal HTN',
    shortTitle: 'SAAG Ascites',
    subtitle: 'Serum-Ascites Albumin Gradient differentiating portal hypertension (≥1.1) from peritoneal carcinomatosis/TB',
    badge: 'AASLD 2021',
    ward: 'internal_medicine',
    keywords: ['saag', 'ascites', 'portal hypertension', 'cirrhosis', 'peritoneal', 'albumin', 'carcinomatosis', 'paracentesis'],
    icon: <Droplets className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'maddrey_mdf',
    title: 'Maddrey Discriminant Function (mDF)',
    shortTitle: 'Maddrey mDF',
    subtitle: 'Alcoholic hepatitis severity index identifying candidates for corticosteroid therapy (mDF ≥ 32)',
    badge: 'AASLD 2019',
    ward: 'internal_medicine',
    keywords: ['maddrey', 'mdf', 'alcoholic hepatitis', 'prothrombin time', 'bilirubin', 'prednisolone', 'steroids', 'lille'],
    icon: <Target className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'four_ts_hit',
    title: '4Ts Score for Heparin-Induced Thrombocytopenia',
    shortTitle: '4Ts HIT Score',
    subtitle: 'Pretest probability scoring for HIT guiding discontinuation of heparin and non-heparin anticoagulation',
    badge: 'ASH 2018',
    ward: 'internal_medicine',
    keywords: ['4ts', 'hit', 'heparin', 'thrombocytopenia', 'argatroban', 'pf4', 'sra', 'platelets', 'thrombosis'],
    icon: <ShieldAlert className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'burch_wartofsky',
    title: 'Burch-Wartofsky Point Scale (BWPS)',
    shortTitle: 'Burch-Wartofsky',
    subtitle: 'Diagnostic likelihood of thyroid storm vs impending storm guiding urgent ICU resuscitation',
    badge: 'ATA Consensus',
    ward: 'internal_medicine',
    keywords: ['burch', 'wartofsky', 'bwps', 'thyroid storm', 'hyperthyroidism', 'propranolol', 'ptu', 'methimazole', 'sski', 'fever', 'tachycardia'],
    icon: <Thermometer className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },

  // Surgery Wiki Tools
  {
    id: 'surgery_wiki_suite',
    title: 'Surgery Clinical Wiki Master Suite',
    shortTitle: 'Surgery Wiki',
    subtitle: 'RIPASA Asian appendicitis, Canadian C-Spine, LRINEC necrotizing fasciitis, Forrest ulcer & Tokyo TG18',
    badge: 'ATLS / TG18 / ESGE',
    ward: 'surgery',
    keywords: ['ripasa', 'canadian c-spine', 'nexus', 'lrinec', 'necrotizing fasciitis', 'forrest', 'peptic ulcer', 'tokyo', 'tg18', 'cholangitis', 'cholecystitis', 'appendicitis'],
    icon: <Flame className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'ripasa_score',
    title: 'RIPASA Asian Appendicitis Score',
    shortTitle: 'RIPASA Score',
    subtitle: 'Asia-validated 16-parameter acute appendicitis score with superior diagnostic accuracy over Alvarado in regional populations',
    badge: 'Asian CPG',
    ward: 'surgery',
    keywords: ['ripasa', 'appendicitis', 'asian population', 'alvarado', 'right lower quadrant', 'rif pain', 'guarding', 'rebound', 'rovsing', 'leukocytosis'],
    icon: <Activity className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'canadian_cspine',
    title: 'Canadian C-Spine Rule & NEXUS',
    shortTitle: 'Canadian C-Spine',
    subtitle: 'Emergency trauma cervical spine clearance decision algorithm minimizing unnecessary CT imaging',
    badge: 'Stiell / JAMA',
    ward: 'surgery',
    keywords: ['c-spine', 'canadian c-spine', 'nexus', 'trauma', 'cervical spine', 'c-collar', 'radiography', 'ct cervical spine', 'range of motion'],
    icon: <ShieldCheck className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },
  {
    id: 'lrinec_score',
    title: 'LRINEC Score (Necrotizing Fasciitis)',
    shortTitle: 'LRINEC Fasciitis',
    subtitle: 'Laboratory Risk Indicator for Necrotizing Fasciitis differentiating severe soft tissue infection from cellulitis',
    badge: 'Wong / CCM',
    ward: 'surgery',
    keywords: ['lrinec', 'necrotizing fasciitis', 'crp', 'wbc', 'hyponatremia', 'soft tissue infection', 'surgical debridement', 'crepitus', 'bullae'],
    icon: <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'forrest_ulcer',
    title: 'Forrest Peptic Ulcer Classification',
    shortTitle: 'Forrest Ulcer',
    subtitle: 'Endoscopic stigmata of recent hemorrhage predicting rebleeding risk and endoscopic intervention',
    badge: 'ESGE / ACG',
    ward: 'surgery',
    keywords: ['forrest', 'peptic ulcer', 'gastrointestinal bleed', 'endoscopy', 'spurting', 'visible vessel', 'adherent clot', 'rebleeding', 'hemoclip'],
    icon: <Activity className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'tokyo_tg18',
    title: 'Tokyo Guidelines (TG18) Cholangitis',
    shortTitle: 'Tokyo TG18',
    subtitle: 'Acute cholangitis & cholecystitis severity grading (I-III) and emergency biliary drainage timing',
    badge: 'TG18 Standards',
    ward: 'surgery',
    keywords: ['tokyo', 'tg18', 'cholangitis', 'cholecystitis', 'biliary drainage', 'ercp', 'charcot triad', 'reynolds pentad', 'sepsis', 'biliary obstruction'],
    icon: <AlertCircle className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },

  // Pediatrics Wiki Tools
  {
    id: 'pediatrics_wiki_suite',
    title: 'Pediatrics Clinical Wiki Master Suite',
    shortTitle: 'Pediatrics Wiki',
    subtitle: 'AAP 2022 Bilirubin Nomogram, Kramer Jaundice, Downes Distress, Bedside PEWS, Jones ARF & WHO MUAC',
    badge: 'AAP 2022 / WHO',
    ward: 'pediatrics',
    keywords: ['bhutani', 'bilirubin', 'kramer', 'jaundice', 'downes', 'respiratory distress', 'pews', 'early warning', 'jones', 'rheumatic fever', 'muac', 'malnutrition'],
    icon: <Baby className="w-5 h-5 text-sky-600 dark:text-sky-400" />,
  },
  {
    id: 'bhutani_nomogram',
    title: 'AAP 2022 Neonatal Bilirubin Nomogram',
    shortTitle: 'AAP Bilirubin',
    subtitle: 'Hour-specific total serum bilirubin phototherapy & double-volume exchange transfusion thresholds',
    badge: 'AAP 2022 Guideline',
    ward: 'pediatrics',
    keywords: ['bhutani', 'bilirubin', 'phototherapy', 'exchange transfusion', 'hyperbilirubinemia', 'kernicterus', 'neonatal jaundice', 'hour-specific'],
    icon: <Baby className="w-5 h-5 text-amber-500 dark:text-amber-400" />,
  },
  {
    id: 'kramer_jaundice',
    title: 'Kramer Cephalocaudal Jaundice Rule',
    shortTitle: 'Kramer Jaundice',
    subtitle: 'Clinical physical exam estimation of neonatal dermal icterus progression from head (Zone 1) to soles (Zone 5)',
    badge: 'Kramer / Lancet',
    ward: 'pediatrics',
    keywords: ['kramer', 'dermal jaundice', 'icterus', 'neonatal', 'cephalocaudal', 'sclera', 'palms', 'soles', 'bili'],
    icon: <Thermometer className="w-5 h-5 text-amber-500 dark:text-amber-400" />,
  },
  {
    id: 'downes_respiratory',
    title: 'Downes Neonatal Respiratory Distress Score',
    shortTitle: 'Downes Distress',
    subtitle: 'Assessment of newborn tachypnea, cyanosis, retractions, grunting & air entry indicating CPAP vs intubation',
    badge: 'Downes Consensus',
    ward: 'pediatrics',
    keywords: ['downes', 'respiratory distress', 'neonatal', 'grunting', 'retractions', 'cyanosis', 'cpap', 'surfactant', 'silverman'],
    icon: <Wind className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />,
  },
  {
    id: 'bedside_pews',
    title: 'Bedside PEWS (Pediatric Early Warning)',
    shortTitle: 'Bedside PEWS',
    subtitle: 'Ward clinical escalation score monitoring behavior, cardiovascular status, and respiratory recession',
    badge: 'Parshuram / CCM',
    ward: 'pediatrics',
    keywords: ['pews', 'early warning', 'rapid response', 'pediatric code', 'deterioration', 'vitals', 'pediatric escalation'],
    icon: <ShieldAlert className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'jones_rheumatic',
    title: 'Modified Jones Criteria (Rheumatic Fever)',
    shortTitle: 'Jones ARF Criteria',
    subtitle: 'AHA 2015 diagnostic criteria for acute rheumatic fever in endemic populations (carditis, polyarthritis, chorea)',
    badge: 'AHA 2015',
    ward: 'pediatrics',
    keywords: ['jones', 'rheumatic fever', 'arf', 'strep', 'aso', 'carditis', 'sydenham chorea', 'erythema marginatum', 'penicillin'],
    icon: <Heart className="w-5 h-5 text-red-500 dark:text-red-400" />,
  },
  {
    id: 'who_muac',
    title: 'WHO MUAC Child Malnutrition Grading',
    shortTitle: 'WHO MUAC',
    subtitle: 'Mid-Upper Arm Circumference screening for Severe Acute Malnutrition (SAM < 115mm) in children 6-59 months',
    badge: 'WHO / UNICEF',
    ward: 'pediatrics',
    keywords: ['muac', 'malnutrition', 'sam', 'mam', 'who growth', 'rutf', 'arm circumference', 'wasting', 'pediatric nutrition'],
    icon: <Activity className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },

  // OB/GYN Wiki Tools
  {
    id: 'obgyn_wiki_suite',
    title: 'OB/GYN Clinical Wiki Master Suite',
    shortTitle: 'OB/GYN Wiki',
    subtitle: 'ROMA Ovarian Algorithm (CA-125 + HE4), Amsel BV criteria, Umbilical Doppler, Swansea AFLP & PALM-COEIN',
    badge: 'ACOG / SGO / FIGO',
    ward: 'obgyn',
    keywords: ['roma', 'ovarian cancer', 'he4', 'amsel', 'bacterial vaginosis', 'umbilical doppler', 'swansea', 'aflp', 'palm-coein', 'aub', 'gyn oncology'],
    icon: <Heart className="w-5 h-5 text-pink-600 dark:text-pink-400" />,
  },
  {
    id: 'roma_score',
    title: 'ROMA Score (Ovarian Malignancy Algorithm)',
    shortTitle: 'ROMA Score',
    subtitle: 'Combines serum HE4 and CA-125 with menopausal status to predict epithelial ovarian cancer in pelvic masses',
    badge: 'ACOG / SGO',
    ward: 'obgyn',
    keywords: ['roma', 'ovarian mass', 'adnexal', 'ca125', 'he4', 'ovarian cancer', 'gyn oncology', 'postmenopausal', 'rmi'],
    icon: <Target className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'amsel_bv',
    title: 'Amsel Criteria for Bacterial Vaginosis',
    shortTitle: 'Amsel BV Criteria',
    subtitle: 'Clinical bedside diagnosis of BV requiring ≥3 of 4 criteria (clue cells, discharge, pH > 4.5, positive whiff test)',
    badge: 'CDC 2021',
    ward: 'obgyn',
    keywords: ['amsel', 'bacterial vaginosis', 'bv', 'clue cells', 'whiff test', 'vaginal discharge', 'metronidazole', 'gardnerella'],
    icon: <Stethoscope className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },
  {
    id: 'umbilical_doppler',
    title: 'Umbilical Artery Doppler Velocimetry',
    shortTitle: 'Umbilical Doppler',
    subtitle: 'S/D ratio & Pulsatility Index assessing placental resistance, Absent (AEDF) & Reversed (REDF) end-diastolic flow',
    badge: 'SMFM Consult #52',
    ward: 'obgyn',
    keywords: ['umbilical doppler', 's/d ratio', 'pulsatility index', 'aedf', 'redf', 'fgr', 'iugr', 'placental insufficiency', 'antenatal surveillance'],
    icon: <Activity className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'swansea_aflp',
    title: 'Swansea Criteria for AFLP',
    shortTitle: 'Swansea AFLP',
    subtitle: 'Clinical & laboratory criteria diagnosing Acute Fatty Liver of Pregnancy (≥6/14) mandating prompt delivery',
    badge: 'Ch’ng / Gut',
    ward: 'obgyn',
    keywords: ['swansea', 'aflp', 'acute fatty liver of pregnancy', 'hypoglycemia', 'uric acid', 'coagulopathy', 'hepatic encephalopathy', 'obstetric emergency'],
    icon: <AlertTriangle className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'palm_coein',
    title: 'FIGO PALM-COEIN AUB Classification',
    shortTitle: 'FIGO PALM-COEIN',
    subtitle: 'Standardized classification system for structural and non-structural causes of abnormal uterine bleeding',
    badge: 'FIGO 2018',
    ward: 'obgyn',
    keywords: ['palm-coein', 'aub', 'abnormal uterine bleeding', 'polyp', 'adenomyosis', 'leiomyoma', 'fibroid', 'coagulopathy', 'ovulatory dysfunction'],
    icon: <Grid3X3 className="w-5 h-5 text-pink-600 dark:text-pink-400" />,
  },

  // ==========================================
  // ALL-IN-ONE CLINICAL CALCULATOR WIKI (MASTER)
  // ==========================================
  {
    id: 'clinical_wiki_master',
    title: 'ALL-IN-ONE Clinical Calculator Wiki',
    shortTitle: 'Clinical Wiki',
    subtitle: 'High-yield scores, formulas & scales across Medicine, Surgery, Pediatrics, and OB-GYN with cutoffs & guidelines',
    badge: '200+ Formulas',
    ward: 'internal_medicine',
    keywords: ['wiki', 'calculator wiki', 'scores', 'scales', 'bode', 'decaf', 'smart-cop', 'ardsnet', 'pesi', 'fe uric acid', 'kt/v', 'rockall', 'aims65', 'lille', 'kings college', 'meld 3', 'nihss', 'hunt hess', 'fisher', 'rankin', 'aspects', 'homa-ir', 'dka', 'frax', 'metabolic syndrome', 'reticulocyte rpi', 'khorana', 'isth dic', 'hscore', 'bsa', 'ciwa-ar', 'naranjo', 'iss trauma', 'fast exam', 'denver bcvi', 'ottawa ankle knee', 'padua vte', 'charlson cci', 'euroscore ii', 'bosniak cysts', 'hinchey diverticulitis', 'milan hcc', 'clavien-dindo', 'gustilo-anderson', 'wagner foot', 'sarnat hie', 'finnegan nas', 'kaiser eos', 'tanner stages', 'waterlow malnutrition', 'who dehydration', 'broselow tape', 'pass asthma', 'rdai bronchiolitis', 'rochester criteria', 'who imci', 'ross heart failure', 'nst evaluation', 'modified bpp', 'upcr proteinuria', 'mgso4 toxicity', 'robson audit', 'endometrial tvus', 'gail breast model', 'amh afc ovarian reserve', 'us mec contraception'],
    icon: <BookOpen className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'bode_index',
    title: 'BODE Index for COPD Mortality',
    shortTitle: 'BODE Index',
    subtitle: '10-point multidimensional score (BMI, FEV1, mMRC, 6MWD) predicting 1- to 4-year survival in COPD',
    badge: 'GOLD / NEJM',
    ward: 'internal_medicine',
    keywords: ['bode', 'copd', 'fev1', 'dyspnea', '6mwd', 'mortality', 'pulmonology'],
    icon: <Wind className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'decaf_score',
    title: 'DECAF Score for AECOPD In-Hospital Mortality',
    shortTitle: 'DECAF Score',
    subtitle: 'Predicts in-hospital mortality in acute exacerbation of COPD using dyspnea, eosinopenia, consolidation, acidemia, and AFib',
    badge: 'BTS / Thorax',
    ward: 'internal_medicine',
    keywords: ['decaf', 'copd', 'exacerbation', 'eosinopenia', 'acidemia', 'mortality'],
    icon: <Activity className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'smart_cop',
    title: 'SMART-COP Pneumonia ICU / Inotrope Score',
    shortTitle: 'SMART-COP',
    subtitle: 'Identifies patients with community-acquired pneumonia who will require intensive respiratory or vasopressor support',
    badge: 'CID / IDSA',
    ward: 'internal_medicine',
    keywords: ['smart-cop', 'pneumonia', 'cap', 'icu', 'inotropes', 'mechanical ventilation'],
    icon: <AlertCircle className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'ardsnet_ibw',
    title: 'ARDSnet Ideal Body Weight & Tidal Volume',
    shortTitle: 'ARDSnet Tidal Vol',
    subtitle: 'Calculates Ideal Body Weight (IBW) and lung-protective tidal volumes (4 - 8 mL/kg IBW) for mechanical ventilation',
    badge: 'ARDSNet / ATS',
    ward: 'internal_medicine',
    keywords: ['ardsnet', 'ibw', 'tidal volume', 'mechanical ventilation', 'ards', 'lung protective'],
    icon: <Wind className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />,
  },
  {
    id: 'pesi_spesi',
    title: 'PESI & Simplified PESI (sPESI) for PE Mortality',
    shortTitle: 'PESI / sPESI',
    subtitle: '30-day mortality risk stratification in acute pulmonary embolism to identify outpatient vs inpatient management',
    badge: 'ESC 2024 / CHEST',
    ward: 'internal_medicine',
    keywords: ['pesi', 'spesi', 'pulmonary embolism', 'pe', 'mortality', 'outpatient'],
    icon: <HeartPulse className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'rockall_score',
    title: 'Rockall Score for Upper GI Bleeding',
    shortTitle: 'Rockall Score',
    subtitle: 'Post-endoscopy risk assessment score predicting rebleeding and mortality in acute upper GI hemorrhage',
    badge: 'BSG / Gut',
    ward: 'internal_medicine',
    keywords: ['rockall', 'ugib', 'upper gi bleed', 'rebleed', 'endoscopy', 'peptic ulcer'],
    icon: <Target className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'aims65',
    title: 'AIMS65 Score for Upper GI Bleed Mortality',
    shortTitle: 'AIMS65 Score',
    subtitle: 'Bedside risk score predicting in-hospital mortality, length of stay, and ICU requirement in acute UGIB',
    badge: 'GIE / ACG',
    ward: 'internal_medicine',
    keywords: ['aims65', 'ugib', 'upper gi bleed', 'inr', 'albumin', 'mortality'],
    icon: <AlertCircle className="w-5 h-5 text-orange-600 dark:text-orange-400" />,
  },
  {
    id: 'nihss',
    title: 'NIH Stroke Scale (NIHSS)',
    shortTitle: 'NIHSS',
    subtitle: '15-item neurological examination scoring acute stroke impairment to guide thrombolysis and thrombectomy',
    badge: 'AHA / ASA',
    ward: 'internal_medicine',
    keywords: ['nihss', 'stroke', 'tpa', 'thrombectomy', 'neurology', 'infarct'],
    icon: <Activity className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'homa_ir',
    title: 'HOMA-IR Insulin Resistance Index',
    shortTitle: 'HOMA-IR',
    subtitle: 'Homeostatic Model Assessment calculating insulin resistance from fasting plasma glucose and fasting insulin',
    badge: 'ADA / Endocrine',
    ward: 'internal_medicine',
    keywords: ['homa', 'homa-ir', 'insulin resistance', 'diabetes', 'metabolic syndrome'],
    icon: <FlaskConical className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },
  {
    id: 'dka_severity',
    title: 'DKA Severity Staging (Mild, Moderate, Severe)',
    shortTitle: 'DKA Severity',
    subtitle: 'ADA classification of Diabetic Ketoacidosis by pH, bicarbonate, anion gap, and mental status',
    badge: 'ADA 2024',
    ward: 'internal_medicine',
    keywords: ['dka', 'ketoacidosis', 'ph', 'bicarbonate', 'anion gap', 'insulin'],
    icon: <Flame className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'frax_risk',
    title: 'FRAX 10-Year Osteoporotic Fracture Risk',
    shortTitle: 'FRAX Fracture',
    subtitle: 'WHO algorithm estimating 10-year probability of hip fracture and major osteoporotic fracture to guide treatment',
    badge: 'WHO / NOF',
    ward: 'internal_medicine',
    keywords: ['frax', 'osteoporosis', 'fracture', 'bone density', 't-score', 'dexa'],
    icon: <Target className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />,
  },
  {
    id: 'ciwa_ar',
    title: 'CIWA-Ar Alcohol Withdrawal Protocol',
    shortTitle: 'CIWA-Ar Protocol',
    subtitle: '10-item clinical withdrawal assessment directing symptom-triggered benzodiazepine therapy',
    badge: 'ASAM',
    ward: 'internal_medicine',
    keywords: ['ciwa', 'alcohol withdrawal', 'delirium tremens', 'benzodiazepines', 'lorazepam'],
    icon: <AlertTriangle className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'iss_score',
    title: 'Injury Severity Score (ISS) & AIS Trauma Staging',
    shortTitle: 'ISS Trauma',
    subtitle: 'Anatomical polytrauma scoring system summing the squares of the highest AIS scores in 3 body regions',
    badge: 'ATLS / AAAM',
    ward: 'surgery',
    keywords: ['iss', 'ais', 'trauma', 'polytrauma', 'major trauma', 'injury severity'],
    icon: <Flame className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'fast_exam',
    title: 'FAST Ultrasound Exam Decision Algorithm',
    shortTitle: 'FAST Exam',
    subtitle: 'Point-of-care 4-window acoustic ultrasound evaluation for free hemoperitoneum or pericardial tamponade',
    badge: 'ATLS 10th Ed',
    ward: 'surgery',
    keywords: ['fast', 'ultrasound', 'hemoperitoneum', 'tamponade', 'morisons pouch', 'laparotomy'],
    icon: <Activity className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'denver_bcvi',
    title: 'Denver Criteria for Blunt Cerebrovascular Injury',
    shortTitle: 'Denver BCVI',
    subtitle: 'Screening criteria determining which blunt trauma patients require screening CTA of the neck for arterial dissection',
    badge: 'EAST / WTA',
    ward: 'surgery',
    keywords: ['denver', 'bcvi', 'cta neck', 'carotid dissection', 'vertebral artery', 'trauma'],
    icon: <ShieldAlert className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'ottawa_rules',
    title: 'Ottawa Ankle and Knee Rules for Radiography',
    shortTitle: 'Ottawa Rules',
    subtitle: 'Near-100% sensitive clinical decision rules determining the necessity of plain radiographs after acute joint trauma',
    badge: 'Ann Emerg Med',
    ward: 'surgery',
    keywords: ['ottawa', 'ankle rule', 'knee rule', 'x-ray', 'malleolar', 'weight bearing'],
    icon: <Stethoscope className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />,
  },
  {
    id: 'padua_score',
    title: 'Padua Prediction Score for Inpatient VTE Risk',
    shortTitle: 'Padua VTE Score',
    subtitle: 'Identifies hospitalized medical/surgical patients at high risk of VTE who benefit from pharmacologic thromboprophylaxis',
    badge: 'CHEST 2012',
    ward: 'surgery',
    keywords: ['padua', 'vte', 'dvt', 'prophylaxis', 'lmwh', 'enoxaparin', 'heparin'],
    icon: <ShieldCheck className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'charlson_cci',
    title: 'Charlson Comorbidity Index (CCI) for Mortality',
    shortTitle: 'Charlson CCI',
    subtitle: 'Age-adjusted multivariable comorbidity score predicting 10-year mortality and perioperative surgical complication risk',
    badge: 'J Chronic Dis',
    ward: 'surgery',
    keywords: ['charlson', 'cci', 'comorbidity', 'mortality', 'pre-op', 'surgical clearance'],
    icon: <Target className="w-5 h-5 text-slate-600 dark:text-slate-400" />,
  },
  {
    id: 'euroscore_ii',
    title: 'EuroSCORE II for Cardiac Surgery Mortality',
    shortTitle: 'EuroSCORE II',
    subtitle: 'Calculates predicted in-hospital operative mortality for adult cardiac surgery (CABG, valve replacement, aortic)',
    badge: 'EACTS / ESC',
    ward: 'surgery',
    keywords: ['euroscore', 'cardiac surgery', 'cabg', 'valve surgery', 'operative mortality'],
    icon: <HeartPulse className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'bosniak_renal',
    title: 'Bosniak Classification of Cystic Renal Masses',
    shortTitle: 'Bosniak Cysts',
    subtitle: 'CT/MRI classification of complex cystic renal masses predicting malignancy risk to direct follow-up vs partial nephrectomy',
    badge: 'AUA / Radiology',
    ward: 'surgery',
    keywords: ['bosniak', 'renal cyst', 'kidney', 'nephrectomy', 'urology', 'rcc'],
    icon: <Target className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'hinchey_diverticulitis',
    title: 'Hinchey Classification of Acute Diverticulitis',
    shortTitle: 'Hinchey Diverticulitis',
    subtitle: 'CT staging of acute perforated colonic diverticulitis from phlegmon (I) to abscess (II) and generalized peritonitis (III/IV)',
    badge: 'WSES 2020',
    ward: 'surgery',
    keywords: ['hinchey', 'diverticulitis', 'abscess', 'peritonitis', 'hartmann', 'colon'],
    icon: <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'milan_criteria',
    title: 'Milan Criteria for HCC Liver Transplantation',
    shortTitle: 'Milan Criteria',
    subtitle: 'Solitary tumor ≤5cm or up to 3 tumors ≤3cm defining eligibility and exception points for liver transplant in HCC',
    badge: 'AASLD / UNOS',
    ward: 'surgery',
    keywords: ['milan', 'hcc', 'hepatoma', 'liver transplant', 'cirrhosis', 'optn'],
    icon: <Target className="w-5 h-5 text-orange-600 dark:text-orange-400" />,
  },
  {
    id: 'gustilo_anderson',
    title: 'Gustilo-Anderson Open Fracture Classification',
    shortTitle: 'Gustilo Open Fx',
    subtitle: 'Classifies open fractures by wound size (I, II, IIIa-c) and vascular status to direct antibiotic coverage and debridement',
    badge: 'OTA / JBJS',
    ward: 'surgery',
    keywords: ['gustilo', 'open fracture', 'orthopedics', 'cefazolin', 'gentamicin', 'debridement'],
    icon: <Activity className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'wagner_diabetic_foot',
    title: 'Wagner Classification for Diabetic Foot Ulcers',
    shortTitle: 'Wagner Foot Ulcer',
    subtitle: 'Grades depth and osteomyelitis/gangrene in diabetic ulcers (Grade 0-5) to guide offloading and surgical debridement',
    badge: 'IWGDF / ADA',
    ward: 'surgery',
    keywords: ['wagner', 'diabetic foot', 'ulcer', 'osteomyelitis', 'gangrene', 'amputation'],
    icon: <AlertCircle className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'sarnat_staging',
    title: 'Sarnat Staging for Neonatal HIE & Cooling',
    shortTitle: 'Sarnat HIE',
    subtitle: 'Clinical staging of neonatal hypoxic-ischemic encephalopathy to determine eligibility for 72-hour therapeutic hypothermia',
    badge: 'AAP / NRP',
    ward: 'pediatrics',
    keywords: ['sarnat', 'hie', 'therapeutic hypothermia', 'cooling', 'asphyxia', 'neonatology'],
    icon: <Baby className="w-5 h-5 text-sky-600 dark:text-sky-400" />,
  },
  {
    id: 'finnegan_nas',
    title: 'Finnegan Neonatal Abstinence Scoring (FNASS)',
    shortTitle: 'Finnegan NAS',
    subtitle: '21-item scoring system quantifying neonatal opioid withdrawal severity to guide supportive care vs oral morphine',
    badge: 'AAP Pediatrics',
    ward: 'pediatrics',
    keywords: ['finnegan', 'nas', 'neonatal abstinence', 'withdrawal', 'morphine', 'methadone'],
    icon: <Activity className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />,
  },
  {
    id: 'neonatal_sepsis_kaiser',
    title: 'Kaiser Neonatal Early-Onset Sepsis (EOS) Risk',
    shortTitle: 'Kaiser EOS Calc',
    subtitle: 'Calculates infant-specific risk of early-onset sepsis per 1000 live births using maternal factors and clinical exam',
    badge: 'AAP 2019',
    ward: 'pediatrics',
    keywords: ['kaiser', 'eos', 'neonatal sepsis', 'gbs', 'chorioamnionitis', 'ampicillin'],
    icon: <ShieldAlert className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'tanner_staging',
    title: 'Tanner Stages of Sexual Maturity Rating (SMR)',
    shortTitle: 'Tanner Stages',
    subtitle: '5-stage physical scale documenting breast, genital, and pubic hair development during adolescent puberty',
    badge: 'AAP Endocrine',
    ward: 'pediatrics',
    keywords: ['tanner', 'puberty', 'sexual maturity', 'thelarche', 'growth spurt'],
    icon: <Target className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'waterlow_malnutrition',
    title: 'Waterlow Classification of Malnutrition (Wasting/Stunting)',
    shortTitle: 'Waterlow Score',
    subtitle: 'Distinguishes acute wasting (weight-for-height) from chronic stunting (height-for-age) in pediatric malnutrition',
    badge: 'WHO / BMJ',
    ward: 'pediatrics',
    keywords: ['waterlow', 'wasting', 'stunting', 'malnutrition', 'pediatric nutrition'],
    icon: <Baby className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />,
  },
  {
    id: 'who_dehydration_plan',
    title: 'WHO Dehydration Assessment & Plans (A, B, C)',
    shortTitle: 'WHO Dehydration',
    subtitle: 'Clinical assessment of diarrhea dehydration directing home fluids (Plan A), ORS 75 mL/kg (Plan B), or IV Ringer’s (Plan C)',
    badge: 'WHO Diarrhea',
    ward: 'pediatrics',
    keywords: ['who', 'dehydration', 'ors', 'plan a', 'plan b', 'plan c', 'diarrhea'],
    icon: <Droplets className="w-5 h-5 text-sky-600 dark:text-sky-400" />,
  },
  {
    id: 'broselow_tape',
    title: 'Broselow Emergency Tape Sizing & Dosing',
    shortTitle: 'Broselow Tape',
    subtitle: 'Length-based emergency reference for pediatric resuscitation drug doses, ETT sizes, and defibrillation energy',
    badge: 'AHA PALS',
    ward: 'pediatrics',
    keywords: ['broselow', 'pals', 'emergency', 'ett', 'defibrillation', 'epinephrine'],
    icon: <HeartPulse className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'pass_asthma',
    title: 'Pediatric Asthma Severity Score (PASS)',
    shortTitle: 'PASS Asthma',
    subtitle: 'Scores wheezing, work of breathing, and tachypnea to guide bronchodilator frequency and systemic corticosteroids',
    badge: 'GINA / Peds ED',
    ward: 'pediatrics',
    keywords: ['pass', 'asthma', 'pediatric asthma', 'wheezing', 'retractions', 'albuterol'],
    icon: <Wind className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'rdai_bronchiolitis',
    title: 'RDAI Score for Pediatric Bronchiolitis',
    shortTitle: 'RDAI Bronchiolitis',
    subtitle: 'Respiratory Distress Assessment Instrument scoring wheezing and retractions in acute viral bronchiolitis (RSV)',
    badge: 'AAP Bronchiolitis',
    ward: 'pediatrics',
    keywords: ['rdai', 'bronchiolitis', 'rsv', 'infant', 'retractions', 'hfnc'],
    icon: <Activity className="w-5 h-5 text-blue-600 dark:text-blue-400" />,
  },
  {
    id: 'rochester_febrile',
    title: 'Rochester Criteria for Febrile Infants (≤60 Days)',
    shortTitle: 'Rochester Criteria',
    subtitle: 'Identifies febrile young infants at low risk for serious bacterial infection (SBI) to avoid lumbar puncture or admission',
    badge: 'AAP 2021',
    ward: 'pediatrics',
    keywords: ['rochester', 'febrile infant', 'sbi', 'fever', 'infant', 'uti'],
    icon: <Thermometer className="w-5 h-5 text-amber-600 dark:text-amber-400" />,
  },
  {
    id: 'who_imci_danger_signs',
    title: 'WHO IMCI General Danger Signs in Children',
    shortTitle: 'IMCI Danger Signs',
    subtitle: 'Screening for 4 cardinal danger signs (inability to drink, persistent vomiting, convulsions, lethargy) mandating referral',
    badge: 'WHO / UNICEF',
    ward: 'pediatrics',
    keywords: ['imci', 'danger signs', 'who', 'pediatric emergency', 'referral'],
    icon: <AlertTriangle className="w-5 h-5 text-red-600 dark:text-red-400" />,
  },
  {
    id: 'ross_heart_failure',
    title: 'Ross Classification for Pediatric Heart Failure',
    shortTitle: 'Ross Heart Failure',
    subtitle: 'Functional classification of infant CHF based on feeding diaphoresis, respiratory rate, and failure to thrive',
    badge: 'ISHLT / Peds',
    ward: 'pediatrics',
    keywords: ['ross', 'heart failure', 'infant', 'chf', 'congenital heart', 'furosemide'],
    icon: <Heart className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'nst_evaluation',
    title: 'Non-Stress Test (NST) Cardiotocography',
    shortTitle: 'NST Evaluation',
    subtitle: 'Interprets antepartum FHR monitoring as Reactive vs Non-Reactive based on gestational age-appropriate accelerations',
    badge: 'ACOG PB 229',
    ward: 'obgyn',
    keywords: ['nst', 'non-stress test', 'fhr', 'accelerations', 'variability', 'fetal monitoring'],
    icon: <HeartPulse className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'modified_bpp',
    title: 'Modified Biophysical Profile (NST + AFI)',
    shortTitle: 'Modified BPP',
    subtitle: 'Combines NST (acute fetal oxygenation) with Amniotic Fluid Index (chronic placental perfusion) for antepartum testing',
    badge: 'ACOG PB 229',
    ward: 'obgyn',
    keywords: ['modified bpp', 'nst', 'afi', 'biophysical profile', 'oligohydramnios'],
    icon: <Droplets className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />,
  },
  {
    id: 'upcr_proteinuria',
    title: 'Spot Urine Protein:Creatinine Ratio (UPCR)',
    shortTitle: 'UPCR Proteinuria',
    subtitle: 'Rapid alternative to 24h collection diagnosing significant proteinuria (UPCR ≥ 0.30 mg/mg) in preeclampsia workup',
    badge: 'ACOG PB 222',
    ward: 'obgyn',
    keywords: ['upcr', 'proteinuria', 'preeclampsia', 'urine protein', 'creatinine'],
    icon: <FlaskConical className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />,
  },
  {
    id: 'mgso4_toxicity',
    title: 'Magnesium Sulfate Toxicity & Monitoring Protocol',
    shortTitle: 'MgSO₄ Toxicity',
    subtitle: 'Safety monitoring of deep tendon reflexes, RR, urine output, and serum Mg during IV infusion for eclampsia seizure prophylaxis',
    badge: 'ACOG PB 222',
    ward: 'obgyn',
    keywords: ['magnesium', 'mgso4', 'toxicity', 'calcium gluconate', 'patellar reflex', 'eclampsia'],
    icon: <AlertTriangle className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'robson_ten_group',
    title: 'Robson 10-Group Cesarean Section Audit',
    shortTitle: 'Robson CS Audit',
    subtitle: 'WHO standardized clinical classification categorizing all deliveries into 10 mutually exclusive groups to audit CS rates',
    badge: 'WHO Statement',
    ward: 'obgyn',
    keywords: ['robson', 'cesarean', 'audit', 'labor', 'c-section', 'vbac', 'who'],
    icon: <Grid3X3 className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
  {
    id: 'endometrial_thickness',
    title: 'Postmenopausal Bleeding Endometrial Thickness',
    shortTitle: 'Endometrial TVUS',
    subtitle: 'TVUS endometrial stripe measurement guiding endometrial biopsy threshold (≤4 mm reassuring vs >4 mm biopsy indicated)',
    badge: 'ACOG CO 734',
    ward: 'obgyn',
    keywords: ['endometrial', 'postmenopausal bleeding', 'biopsy', 'endometrial cancer', 'tvus'],
    icon: <Target className="w-5 h-5 text-rose-600 dark:text-rose-400" />,
  },
  {
    id: 'gail_breast_cancer',
    title: 'Gail Model Breast Cancer Risk Assessment',
    shortTitle: 'Gail Model Risk',
    subtitle: 'Calculates 5-year and lifetime risk of invasive breast cancer to guide chemoprevention (≥1.7%) and screening MRI (≥20%)',
    badge: 'NCI / ASCO',
    ward: 'obgyn',
    keywords: ['gail', 'breast cancer', 'tamoxifen', 'risk', 'mammogram', 'mri'],
    icon: <Heart className="w-5 h-5 text-pink-600 dark:text-pink-400" />,
  },
  {
    id: 'ovarian_reserve_amh',
    title: 'Ovarian Reserve Markers (AMH & Antral Follicles)',
    shortTitle: 'AMH & AFC Reserve',
    subtitle: 'Interprets serum Anti-Müllerian Hormone and Antral Follicle Count to assess follicle pool and IVF response',
    badge: 'ASRM / ESHRE',
    ward: 'obgyn',
    keywords: ['amh', 'afc', 'ovarian reserve', 'dor', 'fertility', 'ivf', 'pcos'],
    icon: <Target className="w-5 h-5 text-purple-600 dark:text-purple-400" />,
  },
  {
    id: 'us_mec_contraception',
    title: 'CDC US MEC Contraceptive Eligibility Criteria',
    shortTitle: 'US MEC Safety',
    subtitle: 'Categories 1 to 4 safety guidance matching clinical conditions (migraine with aura, postpartum, hypertension) to safe contraception',
    badge: 'CDC MMWR',
    ward: 'obgyn',
    keywords: ['mec', 'contraception', 'estrogen', 'migraine with aura', 'iud', 'progestin', 'cdc'],
    icon: <ShieldCheck className="w-5 h-5 text-teal-600 dark:text-teal-400" />,
  },
];

